const Order = require('../../domain/entities/order.entity');
const { NotFoundError } = require('../../domain/errors');

class OrderService {
    constructor(orderRepository) { // ¡Depende de la interfaz!
        this.orderRepository = orderRepository;
    }
    
    async getAllOrders() {
        return this.orderRepository.getAll();
    }

    async getOrderById(id) {
        const order = await this.orderRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }
        return product;
    }

    async createOrder(orderData) {
        // Aquí podría haber lógica de negocio y validaciones
        const orderEntity = new Order(
            null, // ID is null because it will be generated by the database
            orderData.userId,
            orderData.products,
            orderData.total,
            orderData.status
        );
        return this.orderRepository.create(orderEntity);
    }

    async updateOrder(id, orderData) {
        const existingOrder = await this.orderRepository.getById(id);
        if (!existingOrder) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }

        const productEntity = new Product(
            id,
            orderData.userId,
            orderData.products,
            orderData.total,
            orderData.status
        );
        return this.orderRepository.update(id, orderEntity);
    }

    async deleteOrder(id) {
        const order = await this.orderRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }
        return this.orderRepository.delete(id);
    }
}
module.exports = OrderService;